### ISSUE TITLE
Refitter Source Generator - generated code not being picked up by Refit's Source Generator

### ISSUE THREAD

**Issue by guillaumeserale** [christianhelle/refitter#100]
When using the new [Refitter Source Generator](https://github.com/christianhelle/refitter#source-generator) to generate Refit Interfaces and classes, the generated code is not being picked up by Refit's Source Generator:

![image](https://github.com/christianhelle/refitter/assets/6672406/c3e48f23-f702-4806-9122-54d2fd3a59dd)

This makes the Refitter Source Generator unusable for now.

[Link ](https://github.com/guillaumeserale/IssueWithRefit) to repo to reproduce the issue.

Any ideas on how to fix this ?

**Comment by christianhelle** [comment]
Thanks for reporting @guillaumeserale 

the source generator has so far been an experiment that I started playing around with lately

I cloned your example repo and updated the .csproj to this:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit.HttpClientFactory" Version="7.0.0" />
    <PackageReference Include="Refitter.SourceGenerator" Version="0.7.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="ExcludeSourceGeneratedFiles" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
    </ItemGroup>
  </Target>

  <Target Name="IncludeSourceGeneratedFiles" AfterTargets="CoreCompile">
    <ItemGroup>
      <Compile Include="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
    </ItemGroup>
  </Target>

</Project>
```

Which placed the generated files within the project and excludes the files right before compilation to avoid duplicate types. It looks like this in Visual Studio

![image](https://github.com/christianhelle/refitter/assets/710400/6605fada-c96a-4c46-9f9c-0a6230ab27fe)

So the problem here is that I have honestly only really tested that the project output code builds, I don't think I have actually ran any project using the source generated code yet.

You're absolutely right, it doesn't work to run the code at all! I just get this error

```
System.InvalidOperationException: IMyApiClient doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.
   at Refit.RestService.GetGeneratedType(Type refitInterfaceType) in /_/Refit/RestService.cs:line 169
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Refit.RestService.For(Type refitInterfaceType, HttpClient client, IRequestBuilder builder) in /_/Refit/RestService.cs:line 76
   at Refit.RestService.For[T](HttpClient client, IRequestBuilder`1 builder) in /_/Refit/RestService.cs:line 20
   at Refit.HttpClientFactoryExtensions.<>c__2`1.<AddRefitClient>b__2_3(HttpClient client, IServiceProvider serviceProvider) in /_/Refit.HttpClientFactory/HttpClientFactoryExtensions.cs:line 63
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at lambda_method1(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
```

No idea how to fix this yet, or if its even possible to fix it, since I'm not sure how to chain these source generators or how to ensure that Refitter generates code before Refit generate codes

This is definitely an interesting problem! I should probably deprecate the source generator NuGet for now and mark it as invisible

**Comment by christianhelle** [comment]
I found a dirty workaround...

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit.HttpClientFactory" Version="7.0.0" />
    <PackageReference Include="Refitter.SourceGenerator" Version="0.7.2" />
  </ItemGroup>

  <Target Name="ExcludeSourceGeneratedFiles" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/Refitter.SourceGenerators.RefitterSourceGenerator/*.cs" />
    </ItemGroup>
  </Target>

  <Target Name="IncludeSourceGeneratedFiles" AfterTargets="CoreCompile">
    <ItemGroup>
      <Compile Include="$(CompilerGeneratedFilesOutputPath)/**/Refitter.SourceGenerators.RefitterSourceGenerator/*.cs" />
    </ItemGroup>
  </Target>

</Project>
```

**Comment by christianhelle** [comment]
I deprecated ***all versions*** of the source generator in nuget.org and marked them to have critical issues

![image](https://github.com/christianhelle/refitter/assets/710400/fbfa1064-aa47-4e24-9017-9ad659293079)

![image](https://github.com/christianhelle/refitter/assets/710400/a858aaf6-c672-4c4d-bff5-dfc9ddb1817f)

thanks again for bringing this up @guillaumeserale 

I hope there's a solution to this

**Comment by guillaumeserale** [comment]
@christianhelle Thanks for the detailed explanation and analysis. 
I wish I could help with a potential solution, but unfortunately, I am not well-versed in Roslyn's Source Generators 😕.

**Comment by guillaumeserale** [comment]
FYI: There's an [open issue in Roslyn](https://github.com/dotnet/roslyn/issues/57239) about the sequence order of Source Generators.

**Comment by guillaumeserale** [comment]
@christianhelle I've played a bit with your latest change.
If I understand correctly, the classes are generated by `Refitter.SourceGenerator` during the build process into the `Generated` Folder.
Then, `Refit.Generator.InterfaceStubGeneratorV2` picks them up to generate its code.

Pretty clever 👍 

I really wished the Roslyn team would have added some execution priority mechanism in the SourceGenerator.
Until then, what you implemented is the next best thing.

**Comment by christianhelle** [comment]
@guillaumeserale Yes, that was the best I could do for now 😅
