### ISSUE TITLE
Add support for using .refitter file from CLI

### ISSUE THREAD

**Issue by yadanilov19** [christianhelle/refitter#121]
Hi!

Is it possible for add a support for using file from CLI params?
Like this: 
```
refitter ./openapi.json --settings-file cli.json
```
I saw you added .refitter file for setup source generation, but some of the parameters weren't supported in the CLI. For example "naming" param.

It would be soo cool to send just file to the command line instead of passing params.

**Comment by christianhelle** [comment]
Oh that's a great idea! It's not that hard to build either so I'll get started on that in the nearest future!

Thanks for the suggestion @yadanilov19

**Comment by christianhelle** [comment]
@all-contributors please add @yadanilov19 for ideas

**Comment by christianhelle** [comment]
This is implemented in #127
