### ISSUE TITLE
Parameters' casing in openAPI document are not honoured  in Refit interface methods

### ISSUE THREAD

**Issue by guillaumeserale** [christianhelle/refitter#124]
When Refitter generates an operation, the parameter names in the methods are formatted in snakeCase.
Here is an example with `Username` and `Password` parameter:
#### OpenAPI Spec
```javascript
{
  "/user/login": {
    "get": {
      "tags": [
        "user"
      ],
      "summary": "Logs user into the system",
      "description": "",
      "operationId": "loginUser",
      "parameters": [
        {
          "name": "Username",
          "in": "query",
          "description": "The user name for login",
          "required": false,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "Password",
          "in": "query",
          "description": "The password for login in clear text",
          "required": false,
          "schema": {
            "type": "string"
          }
        }
      ],
      ...
    }
  }
}
``` 
#### Generated Code
```c#
        [Get("/user/login")]
        Task<string> LoginUser([Query] string username, [Query] string password);

``` 
#### URL
`http://swagger.io/user/login?username=XXXX&password=XXXX`

This is causing issues in APIs that require the original casing for parameter names ( `Username` instead of `username` and `Password` instead of `password`)

**Comment by christianhelle** [comment]
@guillaumeserale thanks for reporting this! I'll look into this tonight

**Comment by christianhelle** [comment]
I just experimented a bit with the Swagger Petstore v3 example

```sh
$  curl -X 'POST' 'https://petstore3.swagger.io/api/v3/pet/1?NaMe=Velociraptor&StAtUS=Available'
```

returns

```
No name provided
```

I tried it out in Refit and can see that using `[AliasAs()]` in the interface works

```cs 
[Get("/pet/{petId}")]
Task<Pet> GetPetById(long petId);

[Post("/pet/{petId}")]
Task UpdatePetWithForm(
    long petId, 
    [AliasAs("name")][Query] string nAmE, 
    [AliasAs("status")][Query] string StAtUS);
```

in this example

```cs
var client = RestService.For<ISwaggerPetstoreOpenAPI30>("https://petstore3.swagger.io/api/v3");

var pet = await client.GetPetById(1);

Console.WriteLine($"Name: {pet.Name}");
Console.WriteLine($"Status: {pet.Status}");

await client.UpdatePetWithForm(
    petId: pet.Id,
    nAmE: $"{pet.Name} Updated",
    StAtUS: Status.Available.ToString());

pet = await client.GetPetById(1);

Console.WriteLine($"Name: {pet.Name}");
Console.WriteLine($"Status: {pet.Status}");
```

outputs:

```
Name: Velociraptor
Status: Available
Name: Velociraptor Updated
Status: Available
```

I suggest that we keep the "code friendly" camelCase style parameter naming and use `[AliasAs()]` to specify what the spec says the parameter should be called.

What do you think @guillaumeserale ?

**Comment by guillaumeserale** [comment]
@christianhelle yes, I agree; using `[AliasAs()]` seems the proper way to do it. I suggest it should be added only if the parameter name `name` and spec name `nAmE` differ.

**Comment by christianhelle** [comment]
@guillaumeserale my thoughts exactly. No need to use `[AliasAs()]` if the parameter name the same

**Comment by christianhelle** [comment]
Apparently the code was already there, I just had to make sure it respected the original casing
