### ISSUE TITLE
Proposal: filter generated interfaces

### ISSUE THREAD

**Issue by kirides** [christianhelle/refitter#131]
This would allow us to only generate a subset of the interfaces/methods we need.

e.g. App might need "Configuration"-Controller/Group Methods, but not others.

by allowing things like the following, the consumers can specify exactly what they need.
_matches are based on regex_ 
```
--include '^/api/v1/user/.*'
--include '^/api/(?!pet\b)' // include everything that is NOT /api/pet
```

For a less fine grained, but also useful way, we could also add filter for the "Tags" section of an openapi spec.

_matches are based value, case-insensitive_
```
--include-tag User \
--include-tag Configuration
```

**Comment by christianhelle** [comment]
@kirides That's a really good idea!
