### ISSUE TITLE
Unexpected initial token 'Boolean' when populating object

### ISSUE THREAD

**Issue by danpowell88** [christianhelle/refitter#138]
**Describe the bug**
refitter https://api.getport.io/json -o IPortApi.cs
Refitter v0.7.3.37
Support key: 6mxy0om

Error:
Unexpected initial token 'Boolean' when populating object. Expected JSON object or array. Path
'paths./v1/blueprints/{blueprint_identifier}/permissions.patch.requestBody.content.application/json.schema.properties.ad
ditionalProperties', line 1, position 3314.
Error: Could not find color or style 'T'.

**Support Key**: `6mxy0om`

**OpenAPI Specifications**
https://api.getport.io/json

**Comment by christianhelle** [comment]
@danpowell88 Thanks for reporting this

I tried out the JSON file (and the YAML version as well) and loaded into OpenAPI spec validators and they both (JSON and YAML versions) reported 102 errors and 279 warnings.

Unfortunately, there is nothing I can do to get that spec to work but I can look into better error reporting that actually ***attempts*** to write out error details of a bad OpenAPI spec

**Comment by christianhelle** [comment]
@all-contributors please add @danpowell88 for bugs

**Comment by christianhelle** [comment]
In case you're curious about the errors, I used [Hidi](https://github.com/microsoft/OpenAPI.NET/blob/vnext/src/Microsoft.OpenApi.Hidi/readme.md) to validate errors

[Hidi errors](https://github.com/christianhelle/refitter/files/12522954/getport-hidi-errors.txt)

**Comment by christianhelle** [comment]
I implemented [OpenAPI validation](141) today and will include it in the next release. Basically, it prints out errors and warnings in an OpenAPI document so users can reach out to the author of the document to request changes implemented

**Comment by christianhelle** [comment]
There's not much we can do about the specified OpenAPI doc in this issue, so I'm closing this
