### ISSUE TITLE
Mark deprecated operations

### ISSUE THREAD

**Issue by angelofb** [christianhelle/refitter#147]
something like
![immagine](https://github.com/christianhelle/refitter/assets/2032257/28373745-3b18-4dfe-aa94-c721f49e5a5d)

**Comment by angelofb** [comment]
and maybe could be useful the trigger --no-obsolete to skip obsolete operations

**Comment by christianhelle** [comment]
That's a good idea @angelofb 

It looks like you already have the code for it, feel free to make a pull request 😄

**Comment by angelofb** [comment]
ok christian, later this day, I ll try to push it.
