### ISSUE TITLE
Path to OpenAPI spec file is required in CLI command even when using a `--settings-file` parameter.

### ISSUE THREAD

**Issue by Ekkeir** [christianhelle/refitter#149]
A new and a very convenient feature allows us to use refitter file via CLI with a `--settings-file` option in the following manner:
`refitter ./openapi.json --settings-file ./openapi.refitter`.

The path to OpenAPI spec file (`./openapi.json`) cannot be dropped from the CLI command as it results in `Input file is required` error.

At the same time refitter file has an `openApiPath` parameter with seemingly the same meaning. Thus it seems redundant and error-prone to have a mandatory path in a CLI command as it becomes unclear which of the paths would be used in the end - the one in CLI command or the one in .refitter file.

**Comment by christianhelle** [comment]
@Ekkeir thanks for taking the time to report this

This can definitely be improved, and rather easily as well.

I can make the mandatory input file argument be optional so users can decide to specify it via the settings file instead

**Comment by christianhelle** [comment]
@all-contributors please add @Ekkeir for bug

**Comment by Ekkeir** [comment]
> @Ekkeir thanks for taking the time to report this
> 
> This can definitely be improved, and rather easily as well.
> 
> I can make the mandatory input file argument optional so users can decide to specify it via the settings file instead

@christianhelle  Sounds great.
Optionally there could be a warning or an outright error in one of or both of the following cases
- path is configured in both URL and refitter file
- different paths are configured in URL and refitter file, user would (at least) want to know that there's a discrepancy and which path is used 

On the other hand, though, it could be covered by documentation as a declared behaviour instead of runtime error/warning.

**Comment by christianhelle** [comment]
@Ekkeir I think I can find some time to work on this today
