### ISSUE TITLE
Generate Refit interfaces as `partial` by default

### ISSUE THREAD

**Issue by kirides** [christianhelle/refitter#161]
I propose ~~ a `--partial` Flag for the CLI.~~ refit interfaces to be generated as `partial` interfaces by default, which would comply with most other code-generator tools out there and the way the models are generated currently.

Reasoning being, for certain classes we need to add attributes, interfaces or utility methods which is currently not possible without modifying the generated code.

By having `partial` classes for Models and Refit-Interfaces, we can make use of a `generated.additions.cs` (example name) which contains the needed modifications.

```cs
// a.cs
internal partial interface ISomething
{

}

// a.additions.cs
[FancyAttribute("With Value")]
[Headers("X-App: MyApp")]
partial interface ISomething {}

```

**Comment by christianhelle** [comment]
@kirides The models are already partial. 

How about we make the interfaces partial by default as well? I can't really see any reason for not making it partial to begin with
