### ISSUE TITLE
Allow for naming of methods when generating interfaces by endpoint

### ISSUE THREAD

**Issue by Noblix** [christianhelle/refitter#176]
**Is your feature request related to a problem?**
I think it would be nice if it were possible to choose naming for methods when interfaces are generated ByEndpoint. Right now it is only possible to customize method names when all endpoints are in a single interface. When doing it for a single interface the {operationName} is a requirement, but I do not think this should be a requirement since there will only be one method in each interface.

**Describe the solution you'd like**
Example of how this could work:
```
{
    "openApiPath": "./openapi.json",
    "namespace": "Your.Namespace.Of.Choice.GeneratedCode",
    "multipleInterfaces": "ByEndpoint",
    "operationNameTemplate": "ExecuteAsync" // Default is Execute
}
```
The .refitter file above results in the following code:
```
/// <summary>
/// Update an existing pet
/// </summary>
public partial interface IUpdatePetEndpoint
{
    /// <summary>
    /// Update an existing pet by Id
    /// </summary>
    [Put("/pet")]
    Task<Pet> Execute([Body] Pet body);
}

/// <summary>
/// Add a new pet to the store
/// </summary>
public partial interface IAddPetEndpoint
{
    /// <summary>
    /// Add a new pet to the store
    /// </summary>
    [Post("/pet")]
    Task<Pet> Execute([Body] Pet body);
}

...
```

**Comment by christianhelle** [comment]
@all-contributors please add @Noblix for ideas
