### ISSUE TITLE
Single output

### ISSUE THREAD

**Issue by bielik01** [christianhelle/refitter#184]
Why using CLI (reading settings from .reffiter file) I get two outputs?
One in outputFolder specified in settings file, but with name from that file name (i.e. test.refitter -> test.g.cs) and another one named Ouput.cs in directory from which I ran the command?

Please, add outputFileName to .reffiter settings so that only one output is produced.

**Comment by christianhelle** [comment]
@bielik01 thanks for taking the time to report this

The `.g.cs` output file was a remnant of the initial source generator implementation. In the original implementation, which didn't work, the output file was never persisted to disk (the normal behavior for source generators). Unfortunately, source generators ran independently of each other and the Refit source generator didn't know that Refitter generated a Refit interface

I'll fix this by adding the `outputFileName` that you suggest

**Comment by christianhelle** [comment]
@all-contributors please add @bielik01 for bugs

**Comment by bielik01** [comment]
Thanks a lot! I try to keep files in the project to minimum 😅

**Comment by christianhelle** [comment]
@bielik01 Do you use the `Refitter.SourceGenerator` package reference? This does some MSBuild magic that automagically includes any .refitter file as `AdditionalFiles` which allows the Refitter source generator to discover it upon build time, generating the `.g.cs` file. There wouldn't be a need to use the CLI tool if you're already using the source generator

> Thanks a lot! I try to keep files in the project to minimum 😅

Perfectly understandable, I do the same. No code is better and faster than no code :)

**Comment by bielik01** [comment]
Yeah, I just noticed what that package does, it's pure magic! But even then, I kinda want it to have name specified by me 😂

**Comment by christianhelle** [comment]
I'll try to implement this tonight

**Comment by christianhelle** [comment]
@bielik01 This is implemented but not thoroughly tested yet. I'm taking a week few days off for the autumn break to spend some time with the family
