### ISSUE TITLE
Manually run refit generator so the source can be directly added to the compilation rather than writing to a file

### ISSUE THREAD

**Issue by alrz** [christianhelle/refitter#196]
I imagine this is done this way because generators don't have access to eachothers' output.

**Comment by alrz** [comment]
Actually I'm not sure if this is possible. (need to pass a new compilation to the second generator)

**Comment by christianhelle** [comment]
@alrz its exactly as you say, source generators run completely independent of each other. It was originally supposed to work as you mentioned, adding to the compilation.
