### ISSUE TITLE
Allow specifying access modifiers for generated classes

### ISSUE THREAD

**Issue by kirides** [christianhelle/refitter#20]
First off, sorry for feature bombing

It would be very handy to be able to specify the access modifier for the generated DTOs and Clients.

backstory:

In our project, we have modularized everything and try to keep our `public` Api surface as small as possible.
We define most of our classes as `internal` unless they explicitly are needed in other places.

All HTTP calls a module needs and all their DTOs reside in the module and never leave it's scope.

**Comment by christianhelle** [comment]
@kirides I have implemented this and will release it tonight (CEST)
