### ISSUE TITLE
if a path contain colon (":") character then must be replace it

### ISSUE THREAD

**Issue by safakkesikci** [christianhelle/refitter#225]
![bug](https://github.com/christianhelle/refitter/assets/7067252/34be809f-8bfe-47db-8ac8-e5d9c5b64e79)

**Comment by christianhelle** [comment]
@safakkesikci Thanks for taking the time to report this.

Do you mind sharing the OpenAPI spec that had this problem?

**Comment by christianhelle** [comment]
@all-contributors please add @safakkesikci for bugs

**Comment by safakkesikci** [comment]
> @safakkesikci Thanks for taking the time to report this.
> 
> Do you mind sharing the OpenAPI spec that had this problem?

Thank you for the very quick response :)
i use to the SourceGenerator.

Problem: NSwag :/ maybe a workaround can be made.
https://github.com/RicoSuter/NSwag/issues/4188

**swagger doc:**
[customer.json](https://github.com/christianhelle/refitter/files/13423571/customer.json)

**customer.refitter file:**
{
  "openApiPath": "customer.json",
  "namespace": "Customer", 
  "naming": {
    "useOpenApiTitle": false
  },
  "multipleInterfaces": "ByTag", 
  "operationNameTemplate": "{operationName}Async",
   "outputFolder": "../Clients",
  "outputFilename": "Customer.cs",
  "codeGeneratorSettings": { 
    "requiredPropertiesMustBeDefined": true,
    "generateDataAnnotations": true,
    "anyType": "object",
    "dateType": "System.DateTimeOffset",
    "dateTimeType": "System.DateTimeOffset",
    "timeType": "System.TimeSpan",
    "timeSpanType": "System.TimeSpan",
    "arrayType": "System.Collections.Generic.ICollection",
    "dictionaryType": "System.Collections.Generic.IDictionary",
    "arrayInstanceType": "System.Collections.ObjectModel.Collection",
    "dictionaryInstanceType": "System.Collections.Generic.Dictionary",
    "arrayBaseType": "System.Collections.ObjectModel.Collection",
    "dictionaryBaseType": "System.Collections.Generic.Dictionary",
    "propertySetterAccessModifier": "",
    "generateImmutableArrayProperties": false,
    "generateImmutableDictionaryProperties": false,
    "handleReferences": false,
    "jsonSerializerSettingsTransformationMethod": null,
    "generateJsonMethods": false,
    "enforceFlagEnums": false,
    "inlineNamedDictionaries": false,
    "inlineNamedTuples": true,
    "inlineNamedArrays": false,
    "generateOptionalPropertiesAsNullable": false,
    "generateNullableReferenceTypes": false,
    "generateNativeRecords": false,
    "generateDefaultValues": true,
    "inlineNamedAny": false,
    "excludedTypeNames": []
  }
}
