### ISSUE TITLE
Unable to change arrayType to List or IList

### ISSUE THREAD

**Issue by eliyammine** [christianhelle/refitter#255]
**Describe the bug**
When putting arrayType to 'System.Collections.Generic.List' or 'System.Collections.Generic.IList', it stays as ICollection. 

**OpenAPI Specifications**
Here is an example of the one that is failing:

```
 "/Auth/domains": {
   "get": {
     "tags": [
       "Auth"
     ],
     "responses": {
       "200": {
         "description": "Success",
         "content": {
           "text/plain": {
             "schema": {
               "type": "array",
               "items": {
                 "type": "string"
               }
             }
           },
           "application/json": {
             "schema": {
               "type": "array",
               "items": {
                 "type": "string"
               }
             }
           },
           "text/json": {
             "schema": {
               "type": "array",
               "items": {
                 "type": "string"
               }
             }
           }
         }
       }
     }
   }
 },
```

**Additional context**

Ran using: dotnet refitter --skip-validation --settings-file openapi.json

refitterconfig looks like this:
```

{
	"openApiPath": "swagger.json",
	"namespace": "DotNetApp",
	"naming": {
		"useOpenApiTitle": false,
		"interfaceName": "ApiClient"
	},
	"contractsGeneratorSettings": {
		"arrayType": "System.Collections.Generic.List"
	},
	"returnIApiResponse": true
}

```

**Comment by christianhelle** [comment]
@eliyammine thanks for taking the time to report this

Let me see what I can do

By the way, do you have a support key?

**Comment by christianhelle** [comment]
@eliyammine one quick thing I noticed in your `.refitter` config file is that you are using `contractsGeneratorSettings` instead of `codeGeneratorSettings`. Can you try out using `codeGeneratorSettings` ?

**Comment by christianhelle** [comment]
You're right @eliyammine. It seems that in the Refit interface, arrays are generated as `ICollection<T>`. The generated contracts seem to be correct and use `IList`

I'll see what I can do...

**Comment by christianhelle** [comment]
@all-contributors please add @eliyammine for bugs

**Comment by christianhelle** [comment]
@eliyammine I have a fix for `arrayType` in the Refit interface that I will merge in.

I will try resolve all the other `codeGeneratorSettings` return type settings over the Christmas holidays

**Comment by christianhelle** [comment]
@eliyammine I published a pre-release version to NuGet

```sh
dotnet tool install --global Refitter --version 0.8.7.40-preview
```

that contains a fix for this specific problem.

I bumped the target framework to .NET 8.0 since it is now the new recommended LTS version and because .NET 6.0 is going out of support soon

**Comment by eliyammine** [comment]
Thank you for the quick fix! Worked perfectly
