### ISSUE TITLE
File not found when using uri

### ISSUE THREAD

**Issue by SWarnberg** [christianhelle/refitter#258]
**Describe the bug**
When using a URI as input to **Refitter**, a _File not found_ exception is thrown.

Example:
`refitter https://myservice.azurewebsites.net/swagger/v1/swagger.json`

When downloading the same json locally it works. Also, executing `curl https://myservice.azurewebsites.net/swagger/v1/swagger.json` works too.

**Comment by christianhelle** [comment]
@SWarnberg thanks for taking the time to report this

I tried the URI in the description but got an HTTP 403 response. Did you stop the app service?

What version of Refitter are you using? 

Do you have a support key?

Do you know if the URI to the OpenAPI spec returns a redirect response?

**Comment by SWarnberg** [comment]
Sorry, I realized I was using a wrong command session with an old version of Refitter. The latest version works great.
