### ISSUE TITLE
Add support for old core frameworks versions from .net6

### ISSUE THREAD

**Issue by yadanilov19** [christianhelle/refitter#290]
**Is your feature request related to a problem? Please describe.**
I have problems on CI because I still using .net6 for my projects

**Describe the solution you'd like**
just update (if we could) target frameworks field in csprojs of refitter

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by christianhelle** [comment]
@yadanilov19 I have mixed feelings about supporting .NET 6.0 since it's no longer the recommended LTS version, and it's going out of support in November 2024

I never tried publishing .NET tool with multiple target frameworks before, but it's worth a shot. Let me see what I can do

**Comment by yadanilov19** [comment]
thx a lot!
I will test it immediately!

**Comment by yadanilov19** [comment]
Everything works fine with preview version!
