### ISSUE TITLE
Non string/boolean CodeGeneratorSettings are not honored

### ISSUE THREAD

**Issue by david-brink-talogy** [christianhelle/refitter#334]
**Describe the bug**
ExcludedTypeNames is not mapped into the NSwag settings.  This property is of type string[], but types that are not bool/string are skipped by MapCSharpGeneratorSettings.

**Comment by christianhelle** [comment]
Thanks for taking the time to report this @david-brink-talogy

**Comment by christianhelle** [comment]
@all-contributors please add @david-brink-talogy for bugs
