### ISSUE TITLE
`remove-unused-schema` not working for collection-type responses

### ISSUE THREAD

**Issue by kirides** [christianhelle/refitter#352]
**Describe the bug**
Schema that has a collection-type returning response like the following doesn't keep the response classes.

**OpenAPI Specifications**

```yaml
  '/v1/GetCollectionItems':
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TheCollectionItemType'
```

This is due to https://github.com/christianhelle/refitter/blob/30e07cfadfea3ccd76f1f2159309ef9162e63831/src/Refitter.Core/SchemaCleaner.cs#L161 not yielding the `schema.Item`-Property aswell.

NSwag doesn't populate the `schema.Items`-Schema collection, instead it populates the single `schema.Item` for the type.

**Comment by christianhelle** [comment]
Thanks for taking the time to report and fix this @kirides
