### ISSUE TITLE
Asana API "cannot derive from sealed type"

### ISSUE THREAD

**Issue by johnnypea** [christianhelle/refitter#359]
Firstly, thank you for this great tool.

I tried to use "Source Generator" with Asana API https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml , but it fails :(.

```
Refitter.g.cs(40548,36): Error CS0509 : 'Parent4': cannot derive from sealed type 'string'
Refitter.g.cs(41151,26): Warning CS8981 : The type name 'filters' only contains lower-cased ascii characters. Such names may become reserved for the language.
```

Is there a way around this, please?

**Comment by christianhelle** [comment]
Thanks for taking the time to report this @johnnypea 

I'll see what I can do and if I can find some sort of workaround

**Comment by christianhelle** [comment]
@johnnypea NSwag, the tool I use to generate the models doesn't seem to like the spec. 

I tried changing

```yaml
    StatusUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/StatusUpdateBase'
        - type: object
          required:
            - parent
          properties:
            parent:
              allOf:
                - type: string
                  description: >-
                    The id of parent to send this status update to. This can be a
                    project,
                    goal or portfolio.
```

to

```yaml
    StatusUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/StatusUpdateBase'
        - type: object
          required:
            - parent
          properties:
            parent:
              type: string
              description: >-
                The id of parent to send this status update to. This can be a
                project,
                goal or portfolio.
```

to get the generated code to work, but I'm unsure of the consequences of this

**Comment by johnnypea** [comment]
Thank you @christianhelle for looking into this. I guess I don't want to "fix" their specs every time I use them.

BTW when I use the CLI I don't have this problem.

**Comment by christianhelle** [comment]
> Thank you @christianhelle for looking into this. I guess I don't want to "fix" their specs every time I use them.

You're welcome

> BTW when I use the CLI I don't have this problem.

That's interesting, because I only tried it out using the CLI tool and I could easily reproduce your problem...

**Comment by utillity** [comment]
same issue - any solution yet?

**Comment by christianhelle** [comment]
> same issue - any solution yet?

@utillity I haven't looked at this in 2 years. Are there any updates to the Asana API? Maybe the problem has fixed itself. I can take a look at this again if someone can provide me with the latest Asana API OpenAPI spec. 

If the spec linked in the description is the latest one then I can try to give it a shot again

**Comment by christianhelle** [comment]
I'll throw this issue at the Claude and GPT models and see if they come up with a feasible implementation
