### ISSUE TITLE
Add the facility to exclude namespaces from generated code

### ISSUE THREAD

**Issue by dammitjanet** [christianhelle/refitter#362]
**Is your feature request related to a problem? Please describe.**
Generated code or AspNetCore projects that have global using means that the addition of some using namespaces is not required

**Describe the solution you'd like**
Add a configuration to exclude certain 'usings' from generated code, similar to the "additionalNamespaces"  configuration.
Additionally, this feature could support wildcard matching such as:

```
  "excludeNamespaces": [ // Optional
    "System.*"
  ],
```
over
```
  "excludeNamespaces": [ // Optional
    "System.Collections.Generic*",
    "System.Text.Json.Serialization",
    "System.Threading",
    "System.Threading.Tasks",
  ],
```

**Describe alternatives you've considered**
Refitter to read and parse the project config file to automatically exclude any global 'usings' included in the file, and the defaults

**Additional context**
n/a

**Comment by christianhelle** [comment]
That's a good idea! 

Thanks for suggesting this @dammitjanet

**Comment by dammitjanet** [comment]
There will be a PR for this either later today or tomorrow morning, just need to add new Tests and update the docs

**Comment by christianhelle** [comment]
Thanks for the contribution @dammitjanet
