### ISSUE TITLE
Support generating immutable records

### ISSUE THREAD

**Issue by ebarnard** [christianhelle/refitter#407]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to generate immutable records.

NJsonSchema supports this by setting `GenerateNativeRecords = true` and `ClassStyle = CSharpClassStyle.Record` in `CSharpGeneratorSettings`.

**Describe the solution you'd like**
Add support for setting `ClassStyle` in `codeGeneratorSettings` in the `.refitter` file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by christianhelle** [comment]
@ebarnard Thanks for taking the time to suggest this. If NJsonSchema already supports it then it should be trivial to implement. You're more than welcome to try to give it a go and I'll make sure your pull request gets merged in, or I could do it myself.

I'm a bit occupied with work and family these days so it might take a few days for me to build this

**Comment by christianhelle** [comment]
@all-contributors please add @ebarnard for ideas

**Comment by christianhelle** [comment]
@ebarnard I got a bit curious so I looked into this in detail and apparently, Refitter already supports `GenerateNativeRecords` but cannot generate immutable records. The immutable records are only generated when `ClassStyle` is set to `Record`

This feature will only take a couple of minutes to implement so I'll just do it myself

**Comment by christianhelle** [comment]
@ebarnard In the pull request #409, I set the `ClassStyle` to either `POCO` or `Record` depending on whether `GenerateNativeRecords` is set. I'll expose the `ClassStyle` in the .refitter settings file later as that involves a bit more work

**Comment by ebarnard** [comment]
That looks perfect, thank you for looking at this so quickly.

**Comment by christianhelle** [comment]
> That looks perfect, thank you for looking at this so quickly.

@ebarnard you're welcome

**Comment by christianhelle** [comment]
@ebarnard this feature is now released as [v1.1.1](https://github.com/christianhelle/refitter/releases/tag/1.1.1)
