### ISSUE TITLE
Percent symbol '%' can be inserted as a property name

### ISSUE THREAD

**Issue by XeClutch** [christianhelle/refitter#453]
**Describe the bug**
When using the Refitter Source Generator, if a percent symbol is used as a property name in the OpenAPI spec, that same percent symbol will be inserted into the name of the property in the generated C#, violating C# property naming rules.

<details>
<summary>Screenshots</summary>
<img src="https://github.com/user-attachments/assets/3e01e8af-6984-4645-a8c4-39ded537c17f">
</details>

**OpenAPI Specifications**
https://api.percipio.com/reporting/swagger.json

**Comment by christianhelle** [comment]
@XeClutch Thanks for taking the time to report this. I'm surprised but the OpenAPI spec example provided is valid. I'm not sure how to handle such a property name but I'll see what I can do

**Comment by christianhelle** [comment]
@all-contributors please add @XeClutch for bugs

**Comment by christianhelle** [comment]
This is a tough one as I rely completely on NSwag for generating the contracts/models and this needs to be addressed in NSwag instead of Refitter.

**Comment by christianhelle** [comment]
> This is a tough one as I rely completely on NSwag for generating the contracts/models and this needs to be addressed in NSwag instead of Refitter.

Scratch that... we can fix this from Refitter as we use a custom property name generator that addresses this kind of problem. 

@XeClutch I have a fix on the way where the property `% ofVideoOrBook` will be generated as `public string Percent_ofVideoOrBook {get; set; }`. We already handle spaces by replacing them with an underscore, and changing that breaks it for other users
