### ISSUE TITLE
Is it possible to replace the liquid files of NSwag?

### ISSUE THREAD

**Issue by ryanheath** [christianhelle/refitter#459]
NSwag has a bug in their generated code (see [here](https://github.com/RicoSuter/NJsonSchema/issues/1728) and see the [fix](https://github.com/RicoSuter/NJsonSchema/pull/1729))

It unfortunately seems the author is not very actively closing PRs.
Meanwhile I'm looking for options to 'fix' here, if possible?

We could alter the generated code and commit it, but in out CI the code gets generated again.
Also after each update, we would have to alter the code again, which can become cumbersome very fast.

It would be a good alternative if Refitter could 'fix' this issue in the meantime.

**Comment by christianhelle** [comment]
@ryanheath Thanks for taking the time to bring this up.

This is not something I considered, and I don't have any direct need for it either. That said, I'm very open to pull requests, so if you somewhat know what to build, and that your feature doesn't break any existing functionality, then you're more than welcome to submit a pull request and I'll make sure that we get it merged in and released

**Comment by christianhelle** [comment]
@all-contributors please add @ryanheath for ideas
