### ISSUE TITLE
Missing documentation for System.Text.Json polymorphic serialization

### ISSUE THREAD

**Issue by christianhelle** [christianhelle/refitter#467]
The documentation regarding using the feature `--use-polymorphic-serialization` introduced by @ryanheath is lacking

I attempted to update the docs in #466 by copying the text in the `<summary>` code but it doesn't explain much. 

It would be awesome if we could get the same detail level of documentation that we have for using `--use-apizr` that @JeremyBP provided in #432

**Comment by christianhelle** [comment]
@ryanheath I could use some help on this if you're up for it. I don't fully understand the feature yet and some documentation would help me as well 😃

**Comment by ryanheath** [comment]
Sure, I'll look into it.

// Ryan
