### ISSUE TITLE
Add PropertyNameGenerator as an optional Parameter

### ISSUE THREAD

**Issue by fsamiec** [christianhelle/refitter#516]
**Is your feature request related to a problem? Please describe.**
Currently, [CodeGeneratorSettings](https://github.com/christianhelle/refitter/blob/2728ed59ed18e86840faac0ff9e93da434e77574/src/Refitter.Core/CSharpClientGeneratorFactory.cs#L27) does not provide an option to define a custom PropertyNameGenerator. In my projects this does not match the PascalNaming convention, as the properties are named like this:
```csharp
[System.Text.Json.Serialization.JsonPropertyName("business_partner")]
public int Business_partner { get; set; }

[System.Text.Json.Serialization.JsonPropertyName("main_consultant_number")]
public int Main_consultant_number { get; set; }
```

**Describe the solution you'd like**
I would like to see an option in `CodeGeneratorSettings` that allows for the integration of a custom `PropertyNameGenerator` like the given sample below:

```csharp
//Refitter.Core/CSharpClientGeneratorFactory.cs
internal class CSharpClientGeneratorFactory(RefitGeneratorSettings settings, OpenApiDocument document)
{
	public CustomCSharpClientGenerator Create()
    {
		var csharpClientGeneratorSettings = new CSharpClientGeneratorSettings
		{
			CodeGeneratorSettings = { PropertyNameGenerator = settings.CodeGeneratorSettings.PropertyNameGenerator ?? new CustomCSharpPropertyNameGenerator(), },
		};
	}
}
```

```csharp
//Refitter.Core/Settings/RefitGeneratorSettings.cs

/// <summary>
/// Provide settings for Refit generator.
/// </summary>
[ExcludeFromCodeCoverage]
public class RefitGeneratorSettings
{    
	/// <summary>Gets or sets the property name generator.</summary>
	[JsonIgnore]
	public IPropertyNameGenerator PropertyNameGenerator { get; set; }		
}
```

**Describe alternatives you've considered**
NSwag unfortunately does not meet our logging requirements, as we need the method names from the RestMethodInfo.

**Additional context**
If there is any other way to customize the property names please let me know.

/cc @christianerbsmehl

**Comment by christianhelle** [comment]
@fsamiec Thanks for taking the time to report this. Unfortunately, I'm too busy with other things to look into this. If you find a solution yourself and create a pull request, then I will find the time to review and make sure your fix gets merged in and released. Otherwise, this will have to wait a few weeks

/cc @christianerbsmehl

**Comment by fsamiec** [comment]
thank you for merging. 👍
i will add another pull request, based on your feedback.
