### ISSUE TITLE
How to use in class library?

### ISSUE THREAD

**Issue by geometrikal** [christianhelle/refitter#534]
I made a .NET 8 class library with a refitter file and an openapi spec:

* `myapi.refitter`
* `myapi.json`  

The refitter file is simply:

```
{
  "openApiPath": "./myapi.json",
  "namespace": "MyApi",
}
```

and the .csproj file is

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Refit" Version="8.0.0" />
      <PackageReference Include="Refitter.SourceGenerator" Version="1.4.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="*.refitter" />
        <Compile Include="./Generated/*.cs" />
    </ItemGroup>

</Project>

```

When I build the project nothing gets generated however. What am I doing wrong?

CLI version of refitter works fine btw

**Comment by christianhelle** [comment]
@geometrikal thanks for taking the time to report this.

I could reproduce your error and resolve it by removing the unnecessary comma in the `.refitter` file

like this:

```
{
  "openApiPath": "./myapi.json",
  "namespace": "MyApi"
}
```

**Comment by christianhelle** [comment]
@geometrikal I can see some room for improvement on the source generator regarding showing error messages...

When I use the same `.refitter` file with the CLI tool then I get the error message

```sh
$  refitter --settings-file .\myapi.refitter

Error: The JSON object contains a trailing comma at the end which is not supported in this mode. Change the reader options. Path: $ | LineNumber: 3 | BytePositionInLine: 0.
```

**Comment by christianhelle** [comment]
@all-contributors please add @geometrikal for bugs

**Comment by geometrikal** [comment]
@christianhelle Ahh so simple 🤣. Thanks so much.
