### ISSUE TITLE
Two almost identical routes that fail at validation.

### ISSUE THREAD

**Issue by hgdemers** [christianhelle/refitter#551]
I have 2 almost identical routes that fail at validation.

/route/{id} : Id is a guid.
/route/{code} : Code is a string.
The open API seems fine, but the validation fails.

I have to use the --skip-validation parameter but I would rather not.

**Comment by hgdemers** [comment]
First of all, thanks for this wonderful tool. 

Error: The path signature '/weatherforecast/{}' MUST be unique. [#/paths//weatherforecast/{code}]

The openApi file works well in swaggerUI.

[swagger.json](https://github.com/user-attachments/files/18067957/swagger.json)

When using the "--skip-validation" parameter, the generation works fine.

**Comment by christianhelle** [comment]
> First of all, thanks for this wonderful tool.

@hgdemers Thank you for your kind words

> Error: The path signature '/weatherforecast/{}' MUST be unique. [#/paths//weatherforecast/{code}]
> 
> The openApi file works well in swaggerUI.

The file you attached looks correct and [Swagger Validator](https://validator.swagger.io/) doesn't complain either

> When using the "--skip-validation" parameter, the generation works fine.

The Microsoft OpenAPI toolchain is open-source and someone will need to fix this from their side. I'll experiment a bit if I can set any options on the library I use to make it less strict or more correct

Thanks for attaching the OpenAPI spec. I can work with this and I'll see what I can do from the Refitter side

**Comment by christianhelle** [comment]
@all-contributors please add @hgdemers for bugs

**Comment by christianhelle** [comment]
@hgdemers I found an option I could toggle called [ValidationRuleSet](https://learn.microsoft.com/en-us/dotnet/api/microsoft.openapi.validations.validationruleset) in which I can set to be empty. Using an empty validation rule set will still validate that the OpenAPI document is readable, but it will be less strict. Using a completely invalid OpenAPI spec will still fail even with an empty validation rule set

I use a shared reader called [OASReader](https://github.com/christianhelle/oasreader) which supports an OpenAPI spec that uses multiple files, and I just implemented a feature that allows consumers of the library to specify a validation rule set in [this pull request](https://github.com/christianhelle/oasreader/pull/71)

**Comment by hgdemers** [comment]
Wow, that was quick!
Thanks.
