### ISSUE TITLE
Refitter -v not showing version number

### ISSUE THREAD

**Issue by Fargekritt** [christianhelle/refitter#560]
**Describe the bug**
`Refitter -v|--version` is not working

```
refitter -v
Error: You should either specify an input URL/file directly or use specify it in 'openApiPath' from the settings file, not both
```

**Comment by christianhelle** [comment]
LOL! That's a built-in feature in the CLI parser library that I use. It worked at some point, but it's one of those things that I have never tested since it was introduced.

Good catch, @Fargekritt, and thanks for taking the time to report this.
