### ISSUE TITLE
Generated files have inconsistent lined endings 

### ISSUE THREAD

**Issue by damianh** [christianhelle/refitter#57]
**Describe the bug**
The generated files seem to have a mixture different lines endings. This dialog appears everytime a file is opened in VS.

![image](https://github.com/christianhelle/refitter/assets/57436/d245cfcb-0770-4be9-857d-38d7b4c630e3)

Perhaps consider normalizing the line endings to whatever the OS environment the tools is run in :)

**Support Key**: `kedfgny`

**OpenAPI Specifications**
N/A

**Additional context**

**Comment by christianhelle** [comment]
@damianh thanks for taking your time to report this. I think your suggestion is a great idea and I will add this to my to-do list

**Comment by christianhelle** [comment]
Apparently, there are already some convenience methods in the string class to do this called [`ReplaceLineEndings()`](https://learn.microsoft.com/en-us/dotnet/api/system.string.replacelineendings?view=net-6.0#system-string-replacelineendings)

**Comment by christianhelle** [comment]
This issue in resolved in [v0.5.28](https://www.nuget.org/packages/Refitter/0.5.28)

**Comment by damianh** [comment]
Nice thanks!
