### ISSUE TITLE
Model definition with property named System results in class that does not compile

### ISSUE THREAD

**Issue by brease-colin** [christianhelle/refitter#68]
**Describe the bug**
When generating a client for an OpenApi (swagger version 2.0) with a model definition with a property named `System`, the generated code no longer compiles. Reason being that the same class also uses references to other classes from the `System` namespace.

**Support Key**: `mmt1dt0`

**OpenAPI Specifications**
(not the full specs, but this is the gist of it)
```
{
  "swagger": "2.0",
  "info": {
    "title": "XX",
    "version": "0.0.0"
  },
  "host": "x.io",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "definitions": {
    "Dummy": {
      "type": "object",
      "properties": {
        "system": {
          "type": "string",
          "description": "XX"
        }
      },
      "description": "XXX",
      "example": {
        "system": "Dummy"
      }
    }
  }
},
```

**Additional context**
May also be true for some reserved words. System is not really a reserved word, but just not very practical.

**Comment by christianhelle** [comment]
The fix for this is now released and published to [nuget.org](https://www.nuget.org/packages/Refitter/0.5.30) as [v0.5.30](https://github.com/christianhelle/refitter/releases/tag/0.5.30)
